# Generated by Django 3.1.7 on 2021-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('slides_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
            },
        ),
    ]
